# Generated by Django 3.2.8 on 2021-10-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211012_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='credits_at',
            new_name='create_at',
        ),
    ]
